// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMsIs_VRsebgEAJdyzkAbx4LM5R_R9P-I',
    appId: '1:453487252439:web:941060b49b5cc147a77192',
    messagingSenderId: '453487252439',
    projectId: 'mychat-11956',
    authDomain: 'mychat-11956.firebaseapp.com',
    storageBucket: 'mychat-11956.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbejMV6ah8LUSLwFifoN1KyjBCFlWHRnQ',
    appId: '1:453487252439:android:9a6a1dd218fd47aca77192',
    messagingSenderId: '453487252439',
    projectId: 'mychat-11956',
    storageBucket: 'mychat-11956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmVaaywj5HhP3AlrVAO_nsZIetE8t7fNE',
    appId: '1:453487252439:ios:69b8b09700cb44d4a77192',
    messagingSenderId: '453487252439',
    projectId: 'mychat-11956',
    storageBucket: 'mychat-11956.firebasestorage.app',
    iosBundleId: 'com.example.mychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmVaaywj5HhP3AlrVAO_nsZIetE8t7fNE',
    appId: '1:453487252439:ios:69b8b09700cb44d4a77192',
    messagingSenderId: '453487252439',
    projectId: 'mychat-11956',
    storageBucket: 'mychat-11956.firebasestorage.app',
    iosBundleId: 'com.example.mychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMsIs_VRsebgEAJdyzkAbx4LM5R_R9P-I',
    appId: '1:453487252439:web:81ea0b5a36c4b668a77192',
    messagingSenderId: '453487252439',
    projectId: 'mychat-11956',
    authDomain: 'mychat-11956.firebaseapp.com',
    storageBucket: 'mychat-11956.firebasestorage.app',
  );
}
